- package-lock.json
- package.json
It's shorter and less redundant.
> Rename node package from @nasa-gcn/gcn-schema to @nasa-gcn/schema

- gcn/notices/core/DateTime.schema.json
- gcn/notices/core/Localization.schema.json
- gcn/notices/core/Statistics.schema.json
- gcn/notices/fermi/gbm/Trigger.example.json
- gcn/notices/icecube/amon/GoldAndBronze.example.json
- gcn/notices/swift/bat/guano/alert.example.json
- gcn/notices/swift/bat/guano/alert.schema.json
- gcn/notices/swift/bat/guano/loc-arcmin.example.json
- gcn/notices/swift/bat/guano/loc-map.example.json
- gcn/notices/swift/bat/guano/retraction.example.json
Has a GUANO notice schema with 4 example use cases:
Alert
Arcmin Pos
Healpix Pos
Retraction
In addition, it has changes to core schema to fix silly things, and changes to Fermi+IceCube to match.
> Example GUANO notices

- gcn/notices/core/EnergyRange.schema.json
- gcn/notices/fermi/gbm/Trigger.example.json
- gcn/notices/icecube/GoldAndBronze.example.json
- gcn/notices/swift/bat/guano/alert.example.json
- gcn/notices/swift/bat/guano/loc-arcmin.example.json
- gcn/notices/swift/bat/guano/loc-map.example.json
According to high-energy, optical and radio units are added in energy range schema.
@jracusin please review it. 
Below is the attached example file, for such change:
> all observations energy

- gcn/notices/core/Localization.schema.json
In JSON Schema, all fields are optional unless they are required.
These fields can already be omitted. Let's not have the redundant and confusing option of having the fields present but null.
> Remove unions with null

- gcn/notices/core/Localization.schema.json
Based on the information here:  https://json-schema.org/understanding-json-schema/reference/non_json_data.html
> Adds encoded fits file field

- gcn/notices/core/Alert.schema.json
- gcn/notices/fermi/lat/Alert.example.json
- gcn/notices/glowbug/alert.example.json
- gcn/notices/icecube/GoldAndBronze.example.json
- gcn/notices/icecube/GoldAndBronze.example_update.json
Fixes #82.
This peels off one bug fix from #79 and reconciles all affected schema.
CC @blaufuss, @shb46, @Tohuvavohu, because this affects the IceCube, Glowbug, and GUANO schema.
> Rename datetime_of_notice to alert_datetime

- gcn/notices/core/Alert.schema.json
- gcn/notices/fermi/lat/Alert.example.json
- gcn/notices/glowbug/alert.example.json
- gcn/notices/icecube/GoldAndBronze.example.json
- gcn/notices/icecube/GoldAndBronze.example_update.json
- gcn/notices/swift/bat/guano/alert.example.json
- gcn/notices/swift/bat/guano/alert.schema.json
- gcn/notices/swift/bat/guano/loc-arcmin.example.json
- gcn/notices/swift/bat/guano/loc-map.example.json
- gcn/notices/swift/bat/guano/retraction.example.json
Make GUANO notices work with the new flat structure and core schema
Fix Alert.schema.json to have consistent property names
> GUANO notices

- gcn/notices/glowbug/alert.schema.json
- gcn/notices/icecube/GoldAndBronze.schema.json
- gcn/notices/icecube/LvkNuTrackSearch.schema.json
The change from anyOf to allOf fixes the false positives in validation. 
As a note, omitting fields from the objects added with allOf ( example, omitting `alert_type` when using a `$ref` to the core `Alert` schema) is still valid, as these fields are not required.
> anyOfs changed to allOf, small update to schema to fix type problem.

- gcn/notices/icecube/LvkNuTrackSearch.example.json
- gcn/notices/icecube/LvkNuTrackSearch.schema.json
Make it clear that p-values reported (overall search or per-event one…s) can be null.  This happens when a search is not run for selection reasons, or an individual event is not significant in one search or the other.
> Include null as option for p-values

- package.json
Fix a typo in the lint-staged rule for prettier: `*.(json,js,mjs)` should have been `*.{json,js,mjs}`.
> Fix typo so that lint-staged runs prettier

- gcn/notices/einstein_probe/wxt/alert.schema.example.json
- gcn/notices/einstein_probe/wxt/alert.schema.json
As discussed in https://github.com/nasa-gcn/gcn-schema/pull/138 , I create a new PR to add a comment to explain the net_count_rate for WXT of Einstein Probe.
> Einstein Probe: add additional_info about net_count_rate

- gcn/notices/core/Pointing.example.json
- gcn/notices/core/Pointing.schema.json
Rename property (ra, dec) as present in localization schema as well.
https://github.com/nasa-gcn/gcn-schema/issues/145
> pointing schema: rename (ra, dec)

- .github/workflows/release.yml
This will allow us to use the schema as a build-time dependency in Node projects.
> Publish to NPM

- gcn/circulars.example.json
- gcn/circulars.schema.json
Create a JSON Schema for GCN Circulars based on a recent example Circular.
Fixes #152.
Added example for validation purposes.
> Add GCN Circulars schema

- gcn/notices/einstein_probe/wxt/alert.example.json
- gcn/notices/einstein_probe/wxt/alert.schema.json
As discussed in previous PR #155 and #159 ,
> It is necessary to include a property such as the event name or trigger ID as a unique ID, which should be the same across both Notices and Circulars.
we prefer to use trigger id as the unique identifier. This PR add `id` property to EP Notice schema and example file.
> Add EP trigger id

- .github/workflows/validate.yml
- .npmrc
- package-lock.json
- package.json
- update-tags.mjs
- validate.mjs
This fixes validation failures on Windows and on version bumps.
> Run tests on a variety of platforms and Node versions

- gcn/notices/core/Pointing.schema.json
Outdated comment exists, https://github.com/nasa-gcn/gcn-schema/issues/177. 
It directs to Attibutes.Schema.Json, which doesn't even exist.
> Not required comment: Pointing.Schema.Json

- gcn/notices/icecube/lvk_nu_track_search.example.json
- gcn/notices/icecube/lvk_nu_track_search.schema.json
Add unique identifier to each LVK coincident neutrino reported in IceCube LVK Alert Nu Track Search
notices.
Resolves #206
Simple expansion of schema, with updated example.
> Add a unique ID to each coincident neutrino location shared.

- gcn/circulars.schema.json
Some circulars will not have an eventId so it is not a required field.
Resolves #209
> make eventId not required

- gcn/notices/core/Reporter.schema.json
The physical type (energy, wavelength, frequency) is implicit in the units.
> Remove spectrum enum
